apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: sosmed-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sosmed-app
  type: LoadBalancer
status:
  loadBalancer: {}
