apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosmed-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sosmed-app
  template:
    metadata:
      labels:
        app: sosmed-app
    spec:
      containers:
      - name: sosmed-app
        image: giovana02/sosmed
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: cmap-coba
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: cmap-coba
                key: DB_NAME
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: cmap-coba
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: cmap-coba
                key: DB_PASSWORD
