apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: secret-sosmed
  name: secret-sosmed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-sosmed
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: secret-sosmed
    spec:
      containers:
      - image: giovana02/sosmed
        name: sosmed
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: cmap-sosmed
                key: DB_HOST          
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: cmap-sosmed
                key: DB_NAME
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: cmap-sosmed
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-sosmed
                key: DB_PASSWORD        
        resources: {}
status: {}
