apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cmap-sosmed
data:
  DB_HOST: rds-jakarta.c1h14jljsded.ap-southeast-3.rds.amazonaws.com
  DB_NAME: sosmed
  DB_USERNAME: admin
  DB_PASSWORD: favianhugo
